# Generated by Django 4.0.5 on 2022-06-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('user_phone', models.IntegerField(max_length=12)),
                ('user_facebook', models.CharField(max_length=200)),
                ('user_country', models.CharField(max_length=50)),
                ('user_birthday', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
