# Generated by Django 4.0.5 on 2022-07-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_user_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_balance',
            field=models.IntegerField(default=1000000),
        ),
    ]
